version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - lll
  settings:
    lll:
      tab-width: 4
      line-length: 120

issues:
  max-issues-per-linter: 0
  max-same-issues: 0